### ISSUE TITLE
Status Code 200 wird zurück gegben, wenn das Abschließen eines Lernelements fehl schlägt

### ISSUE THREAD

**Issue by Glutamat42** [ProjektAdLer/AdLerBackend#18]
PATCH
    https://api.projekt-adler.eu/api/Elements/World/215/Element/1
Status
200

Aber das Element wurde nicht abgeschlossen. Im aktuellen Beispiel ist die Abschlussbedingung des Lernelements fälschlicherweiße auf "manual" gesetzt, statt auf "on view"

**Comment by philgei** [comment]
Issue an 3d stellen. Im ScoreElementUsecase wird der Return von meinem call nicht gelesen
