### ISSUE TITLE
In der Tabelle Worlds wird "Id" nicht mehr auf AUTO_INCREMENT gesetzt

### ISSUE THREAD

**Issue by Glutamat42** [ProjektAdLer/AdLerBackend#19]
Seit Version 2.4.0 fehlt bei einer neu initialisierten Datenbank das Attribut AUTO_INCREMENT, weshalb es nicht mehr möglich ist das Backend "neu zu installieren".

Gleiches bei der Tabelle H5PLocationEntity

**Comment by philgei** [comment]
SQLite hat kein Auto Increment

**Comment by philgei** [comment]
Fixed. Release 2.4.1
