### ISSUE TITLE
Datenleiche in Moodle bei Datenbankfehler

### ISSUE THREAD

**Issue by Glutamat42** [ProjektAdLer/AdLerBackend#21]
Schlägt das Anlegen eines Eintrages in der World-Tabelle fehl (auto increment fehlt) wird in Moodle der Kurs angelegt, aber nicht im Backend (schlägt ja fehl). Der bereits angelegte Kurs in Moodle wird aber nicht gelöscht und bleibt als Datenleiche bestehen

**Comment by philgei** [comment]
fixed. Wird im nächsten Release raus gehen
